### ISSUE TITLE
getClusterInfo - missing input

### ISSUE THREAD

**Issue by leppott** [leppott/CASTfxn#76]
**Describe the bug**
getClusterInfo function is missing data.cluster as an input.

**To Reproduce**
From Report.

![image](https://user-images.githubusercontent.com/24276278/59207658-77de4280-8b75-11e9-99d5-01fcb0974b47.png)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ALincolnTt** [comment]
data.cluster added to argument list.
